In [1]:
import cv2 as cv
import numpy as np


In [2]:
import matplotlib as mp

In [3]:
print(((251*173)/256)-256)
print(np.multiply(251,173))

-86.37890625
43423


In [4]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print(x1,x2)
np.multiply(x1,x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] [0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])