In [1]:

import numpy as np
import cv2 as cv2




path2="archive/data/messi5.jpg"
roi_img=cv2.imread(path2)
print(roi_img)



replicate= cv2.copyMakeBorder(roi_img,10,10,10,10,cv2.BORDER_REPLICATE)

cv2.imshow("replicate",replicate)

print(replicate[1,:10,:])
# print(replicate[1,10:,:])
# print(replicate[1,-10:,:])

[[[ 39  43  44]
  [ 42  46  47]
  [ 44  47  52]
  ...
  [ 57  55  55]
  [ 55  53  53]
  [ 52  50  50]]

 [[ 37  40  44]
  [ 42  45  49]
  [ 46  49  54]
  ...
  [ 62  60  60]
  [ 60  58  58]
  [ 57  55  55]]

 [[ 41  45  50]
  [ 46  50  55]
  [ 51  55  60]
  ...
  [ 64  63  65]
  [ 63  62  64]
  [ 60  59  61]]

 ...

 [[ 56 143  99]
  [ 48 133  89]
  [ 49 129  86]
  ...
  [ 60 134  92]
  [ 63 134  94]
  [ 73 145 103]]

 [[ 54 138  96]
  [ 59 141  99]
  [ 50 130  87]
  ...
  [ 56 132  91]
  [ 69 142 104]
  [ 64 137  97]]

 [[ 45 129  87]
  [ 58 140  98]
  [ 71 151 108]
  ...
  [ 49 124  86]
  [ 52 125  87]
  [ 51 124  86]]]
[[39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]
 [39 43 44]]


: 

SyntaxError: invalid syntax (3736404971.py, line 1)

: 